server:
  port: 8061
spring:
  application:
    name: product-query-service
  kafka:
    consumer:
      bootstrap-servers:
        - localhost:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.javacodewiz.dto
  datasource:
    url: jdbc:mysql://localhost:3306/kafka
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


